import os
import json

def write_notebook(filepath, cells):
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 2
    }
    
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=2)
    print(f"Created notebook: {filepath}")

# ==========================================
# Notebook 1: 01_raw_sync_audit.ipynb
# ==========================================
nb1_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 1: Raw Data Synchronization Audit\n",
            "This notebook scans the raw dataset directories, identifies modality presence, and checks duration synchronization across Video, Audio, and Physiological signals."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Initializing system environment and path imports...\")\n",
            "import os\n",
            "import sys\n",
            "import pandas as pd\n",
            "\n",
            "sys.path.append(os.path.abspath('../'))\n",
            "from src.data.loader import RawDataLoader\n",
            "print(\"[STATUS] System paths configured successfully.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Checking directory configuration...\")\n",
            "base_dir = '/content/drive/MyDrive/Multimodal_stress_Detection/' if os.path.exists('/content/drive') else '../../'\n",
            "print(f\"[INFO] Target base directory detected: {os.path.abspath(base_dir)}\")\n",
            "\n",
            "print(\"[BACKGROUND] Instantiating RawDataLoader and scanning folders recursively...\")\n",
            "loader = RawDataLoader(base_dir)\n",
            "summary, detailed_df = loader.run_synchronization_audit()\n",
            "print(\"[STATUS] Scanning complete. Multimodal keys grouped successfully.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Formatting raw alignment metrics summary...\")\n",
            "print(\"\\n==================================================\")\n",
            "print(\"RAW DATA SYNCHRONIZATION AUDIT REPORT\")\n",
            "print(\"==================================================\")\n",
            "for k, v in summary.items():\n",
            "    print(f\"{k:25}: {v}\")\n",
            "print(\"==================================================\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Preparing directory paths for CSV audit reports...\")\n",
            "os.makedirs('../reports/synchronization/', exist_ok=True)\n",
            "\n",
            "print(\"[BACKGROUND] Writing file-level audit details to raw_files_alignment_audit.csv...\")\n",
            "detailed_df.to_csv('../reports/synchronization/raw_files_alignment_audit.csv', index=False)\n",
            "\n",
            "print(\"[BACKGROUND] Writing metric summary to synchronization_report.csv...\")\n",
            "report_df = pd.DataFrame([{\"metric\": k, \"value\": v} for k, v in summary.items()])\n",
            "report_df.to_csv('../reports/synchronization/synchronization_report.csv', index=False)\n",
            "\n",
            "print(\"[STATUS] Reports successfully saved under early_fusion/reports/synchronization/\")"
        ]
    }
]

# ==========================================
# Notebook 2: 02_extract_and_align.ipynb
# ==========================================
nb2_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 2 & 3: Clean Alignment, Extraction and Split Setup\n",
            "This notebook loads the pre-extracted windowed features, performs inner-joins on composite key windows, and splits subjects into train/val/test groups."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Importing environment modules...\")\n",
            "import os\n",
            "import sys\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "\n",
            "sys.path.append(os.path.abspath('../'))\n",
            "from src.data.split import SubjectSplitter\n",
            "print(\"[STATUS] Environment successfully initialized.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Searching for pre-extracted datasets...\")\n",
            "# Drive vs local check\n",
            "search_paths = [\n",
            "    '../../dataset_extracted/',\n",
            "    '../../certified_data/',\n",
            "    '../data/raw/'\n",
            "]\n",
            "extracted_dir = None\n",
            "for p in search_paths:\n",
            "    if os.path.exists(p) and any(f.endswith('.csv') for f in os.listdir(p)):\n",
            "        extracted_dir = p\n",
            "        break\n",
            "\n",
            "if extracted_dir is None:\n",
            "    print(\"[WARNING] Pre-extracted feature CSV files not found. Creating mock data for dry-run...\")\n",
            "    os.makedirs('../data/raw/', exist_ok=True)\n",
            "    # Mock feature tables\n",
            "    df_face = pd.DataFrame({\n",
            "        'subject_id': ['s01']*5 + ['s02']*5 + ['s03']*5 + ['s04']*5 + ['s05']*5,\n",
            "        'task_id': ['Stroop']*25,\n",
            "        'window_index': list(range(5))*5,\n",
            "        'label': [1]*10 + [0]*15,\n",
            "        **{f'face_{i}': np.random.randn(25) for i in range(18)}\n",
            "    })\n",
            "    df_voice = pd.DataFrame({\n",
            "        'subject_id': ['s01']*5 + ['s02']*5 + ['s03']*5 + ['s04']*5 + ['s05']*5,\n",
            "        'task_id': ['stroop']*25,\n",
            "        'window_index': list(range(5))*5,\n",
            "        **{f'voice_{i}': np.random.randn(25) for i in range(12)}\n",
            "    })\n",
            "    df_physio = pd.DataFrame({\n",
            "        'subject_id': ['S01']*5 + ['S02']*5 + ['S03']*5 + ['S04']*5 + ['S05']*5,\n",
            "        'task_id': ['STROOP']*25,\n",
            "        'window_index': list(range(5))*5,\n",
            "        **{f'physio_{i}': np.random.randn(25) for i in range(5)}\n",
            "    })\n",
            "    df_face.to_csv('../data/raw/face_certified.csv', index=False)\n",
            "    df_voice.to_csv('../data/raw/voice_certified.csv', index=False)\n",
            "    df_physio.to_csv('../data/raw/physio_certified.csv', index=False)\n",
            "    extracted_dir = '../data/raw/'\n",
            "\n",
            "print(f\"[INFO] Loading pre-extracted features from directory: {os.path.abspath(extracted_dir)}\")\n",
            "\n",
            "# Load files by matching patterns\n",
            "files = os.listdir(extracted_dir)\n",
            "f_csv = [f for f in files if 'face' in f.lower() and f.endswith('.csv')][0]\n",
            "v_csv = [f for f in files if 'voice' in f.lower() and f.endswith('.csv')][0]\n",
            "p_csv = [f for f in files if 'physio' in f.lower() and f.endswith('.csv')][0]\n",
            "\n",
            "df_face = pd.read_csv(os.path.join(extracted_dir, f_csv))\n",
            "df_voice = pd.read_csv(os.path.join(extracted_dir, v_csv))\n",
            "df_physio = pd.read_csv(os.path.join(extracted_dir, p_csv))\n",
            "print(f\"[STATUS] Datasets loaded. Face Shape: {df_face.shape}, Voice Shape: {df_voice.shape}, Physio Shape: {df_physio.shape}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Normalizing task IDs and keys structure...\")\n",
            "for df in [df_face, df_voice, df_physio]:\n",
            "    df['subject_id'] = df['subject_id'].astype(str).str.lower().str.strip()\n",
            "    df['task_id'] = df['task_id'].astype(str).str.lower().str.strip()\n",
            "    df['window_index'] = df['window_index'].astype(int)\n",
            "    df['sync_key'] = df['subject_id'] + \"_\" + df['task_id'] + \"_\" + df['window_index'].astype(str)\n",
            "\n",
            "print(\"[BACKGROUND] Aligning modalities via left-joining using physio as base...\")\n",
            "# Drop metadata columns from other dataframes to keep merged table clean\n",
            "df_face_clean = df_face.drop(columns=['subject_id', 'task_id', 'video_id', 'window_index', 'window_start', 'window_end', 'label'], errors='ignore')\n",
            "df_voice_clean = df_voice.drop(columns=['subject_id', 'task_id', 'video_id', 'window_index', 'window_start', 'window_end', 'label'], errors='ignore')\n",
            "\n",
            "synced_df = df_physio.merge(df_face_clean, on='sync_key', how='left')\n",
            "synced_df = synced_df.merge(df_voice_clean, on='sync_key', how='left')\n",
            "\n",
            "print(f\"[STATUS] Modality alignment finished. Synced samples remaining: {synced_df.shape[0]}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Performing Subject-Level Baseline Normalization...\")\n",
            "# Define all feature columns\n",
            "face_cands = ['left_ear', 'right_ear', 'avg_ear', 'blink_velocity', 'brow_descent_left', 'brow_descent_right', 'brow_asymmetry', 'lip_compression', 'jaw_tension', 'mouth_corner_pull', 'forehead_tension', 'face_height_norm', 'head_tilt', 'temporal_x_var', 'temporal_y_var', 'eye_openness_ratio', 'landmark_confidence', 'nose_wrinkle']\n",
            "voice_cands = ['f0_mean', 'f0_std', 'f0_range', 'jitter_percent', 'shimmer_db', 'hnr', 'speaking_rate_proxy', 'voice_intensity', 'high_freq_ratio', 'spectral_flux', 'pause_ratio', 'voiced_fraction']\n",
            "physio_cands = ['ecg_rate_mean', 'ecg_hrv_rmssd', 'ecg_hrv_sdnn', 'eda_scl_mean', 'resp_rate_mean']\n",
            "\n",
            "face_cols = [c for c in face_cands if c in synced_df.columns]\n",
            "voice_cols = [c for c in voice_cands if c in synced_df.columns]\n",
            "physio_cols = [c for c in physio_cands if c in synced_df.columns]\n",
            "feature_cols = face_cols + voice_cols + physio_cols\n",
            "\n",
            "# Calculate resting baseline averages per subject during 'baseline' task\n",
            "baseline_df = synced_df[synced_df['task_id'] == 'baseline']\n",
            "subject_baselines = baseline_df.groupby('subject_id')[feature_cols].mean()\n",
            "# Overall subject mean as fallback if 'baseline' task is missing\n",
            "subject_overall_means = synced_df.groupby('subject_id')[feature_cols].mean()\n",
            "\n",
            "normalized_rows = []\n",
            "for sub in synced_df['subject_id'].unique():\n",
            "    sub_df = synced_df[synced_df['subject_id'] == sub].copy()\n",
            "    # Get baseline vector for this subject\n",
            "    if sub in subject_baselines.index and not subject_baselines.loc[sub].isna().any():\n",
            "        sub_base = subject_baselines.loc[sub]\n",
            "    else:\n",
            "        sub_base = subject_overall_means.loc[sub]\n",
            "        \n",
            "    # Subtract baseline vector from all tasks\n",
            "    sub_df[feature_cols] = sub_df[feature_cols] - sub_base\n",
            "    normalized_rows.append(sub_df)\n",
            "    \n",
            "synced_df = pd.concat(normalized_rows, ignore_index=True)\n",
            "print(\"[STATUS] Baseline normalization complete. Features converted to relative change indices.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Executing subject-independent split logic...\")\n",
            "splitter = SubjectSplitter(random_seed=42)\n",
            "unique_subjects = synced_df['subject_id'].unique()\n",
            "splits = splitter.create_splits(unique_subjects)\n",
            "\n",
            "os.makedirs('../data/splits/', exist_ok=True)\n",
            "pd.DataFrame(splits['train']).to_csv('../data/splits/train_ids.csv', index=False, header=['subject_id'])\n",
            "pd.DataFrame(splits['val']).to_csv('../data/splits/val_ids.csv', index=False, header=['subject_id'])\n",
            "pd.DataFrame(splits['test']).to_csv('../data/splits/test_ids.csv', index=False, header=['subject_id'])\n",
            "\n",
            "print(\"\\n==================================================\")\n",
            "print(\"LOSO SPLIT REPORT\")\n",
            "print(\"==================================================\")\n",
            "print(f\"Train subjects: {splits['train']}\")\n",
            "print(f\"Val subjects:   {splits['val']}\")\n",
            "print(f\"Test subjects:  {splits['test']}\")\n",
            "print(\"==================================================\")\n",
            "\n",
            "print(\"[BACKGROUND] Splitting dataset into clean train, val, and test partitions...\")\n",
            "df_train = synced_df[synced_df['subject_id'].isin(splits['train'])]\n",
            "df_val = synced_df[synced_df['subject_id'].isin(splits['val'])]\n",
            "df_test = synced_df[synced_df['subject_id'].isin(splits['test'])]\n",
            "\n",
            "print(\"[BACKGROUND] Saving partitioned datasets to data/processed/...\")\n",
            "os.makedirs('../data/processed/train/', exist_ok=True)\n",
            "os.makedirs('../data/processed/val/', exist_ok=True)\n",
            "os.makedirs('../data/processed/test/', exist_ok=True)\n",
            "os.makedirs('../data/processed/metadata/', exist_ok=True)\n",
            "\n",
            "df_train.to_csv('../data/processed/train/train_synced.csv', index=False)\n",
            "df_val.to_csv('../data/processed/val/val_synced.csv', index=False)\n",
            "df_test.to_csv('../data/processed/test/test_synced.csv', index=False)\n",
            "synced_df.to_csv('../data/processed/metadata/synced_dataset.csv', index=False)\n",
            "print(\"[STATUS] Split datasets successfully saved to data/processed/ subfolders.\")"
        ]
    }
]

# ==========================================
# Notebook 3: 03_train_models.ipynb
# ==========================================
nb3_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 5 & 6: Train Baseline and FlexiModal MoE Models\n",
            "Prepares sequential input window dataloaders, initializes model modules, and executes optimizer training runs."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Importing training and model modules...\")\n",
            "import os\n",
            "import sys\n",
            "import torch\n",
            "import torch.nn as nn\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "import warnings\n",
            "from torch.utils.data import Dataset, DataLoader\n",
            "\n",
            "warnings.filterwarnings('ignore')\n",
            "\n",
            "sys.path.append(os.path.abspath('../'))\n",
            "from src.models.baselines import EarlyFusionClassifier, GatedFusionClassifier, CrossAttentionFusionClassifier\n",
            "from src.models.fleximodal_moe import FlexiModalMoE\n",
            "from src.training.trainer import MultimodalTrainer\n",
            "print(\"[STATUS] Deep learning imports verified successfully.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Loading partitioned datasets directly...\")\n",
            "df_train = pd.read_csv('../data/processed/train/train_synced.csv')\n",
            "df_val = pd.read_csv('../data/processed/val/val_synced.csv')\n",
            "\n",
            "print(f\"[INFO] Partitioned splits loaded. Train count: {df_train.shape[0]} | Val count: {df_val.shape[0]}\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Defining sequential PyTorch Dataset wrappers...\")\n",
            "class SyncedDataset(Dataset):\n",
            "    def __init__(self, df, seq_len=5, is_train=False):\n",
            "        self.df = df.reset_index(drop=True)\n",
            "        self.seq_len = seq_len\n",
            "        self.is_train = is_train\n",
            "        # Locate feature columns dynamically supporting both real and mock columns\n",
            "        face_cands = ['left_ear', 'right_ear', 'avg_ear', 'blink_velocity', 'brow_descent_left', 'brow_descent_right', 'brow_asymmetry', 'lip_compression', 'jaw_tension', 'mouth_corner_pull', 'forehead_tension', 'face_height_norm', 'head_tilt', 'temporal_x_var', 'temporal_y_var', 'eye_openness_ratio', 'landmark_confidence', 'nose_wrinkle']\n",
            "        self.face_cols = [c for c in face_cands if c in df.columns]\n",
            "        if len(self.face_cols) == 0:\n",
            "            self.face_cols = [c for c in df.columns if c.startswith('face_') and c not in ['face_mask']]\n",
            "            \n",
            "        voice_cands = ['f0_mean', 'f0_std', 'f0_range', 'jitter_percent', 'shimmer_db', 'hnr', 'speaking_rate_proxy', 'voice_intensity', 'high_freq_ratio', 'spectral_flux', 'pause_ratio', 'voiced_fraction']\n",
            "        self.voice_cols = [c for c in voice_cands if c in df.columns]\n",
            "        if len(self.voice_cols) == 0:\n",
            "            self.voice_cols = [c for c in df.columns if c.startswith('voice_') and c not in ['voice_mask']]\n",
            "            \n",
            "        physio_cands = ['ecg_rate_mean', 'ecg_hrv_rmssd', 'ecg_hrv_sdnn', 'eda_scl_mean', 'resp_rate_mean']\n",
            "        self.physio_cols = [c for c in physio_cands if c in df.columns]\n",
            "        if len(self.physio_cols) == 0:\n",
            "            self.physio_cols = [c for c in df.columns if c.startswith('physio_') and c not in ['physio_mask']]\n",
            "        \n",
            "    def __len__(self):\n",
            "        return len(self.df)\n",
            "        \n",
            "    def __getitem__(self, idx):\n",
            "        # Force conversion to float32 and handle NaNs dynamically from left join\n",
            "        face_nans = self.df.loc[idx, self.face_cols].isna().any()\n",
            "        voice_nans = self.df.loc[idx, self.voice_cols].isna().any()\n",
            "        physio_nans = self.df.loc[idx, self.physio_cols].isna().any()\n",
            "        \n",
            "        face_mask = 0.0 if face_nans else 1.0\n",
            "        voice_mask = 0.0 if voice_nans else 1.0\n",
            "        physio_mask = 0.0 if physio_nans else 1.0\n",
            "        \n",
            "        # Randomly drop modalities during training to force model to learn actual features\n",
            "        if self.is_train:\n",
            "            if np.random.rand() < 0.3:\n",
            "                face_mask = 0.0\n",
            "            if np.random.rand() < 0.3:\n",
            "                voice_mask = 0.0\n",
            "            if np.random.rand() < 0.3:\n",
            "                physio_mask = 0.0\n",
            "            # Retain at least one active modality\n",
            "            if face_mask == 0.0 and voice_mask == 0.0 and physio_mask == 0.0:\n",
            "                physio_mask = 1.0\n",
            "                \n",
            "        face_mask_t = torch.tensor(face_mask, dtype=torch.float32)\n",
            "        voice_mask_t = torch.tensor(voice_mask, dtype=torch.float32)\n",
            "        physio_mask_t = torch.tensor(physio_mask, dtype=torch.float32)\n",
            "        \n",
            "        face_vals = np.nan_to_num(self.df.loc[idx, self.face_cols].values.astype(np.float32), nan=0.0)\n",
            "        voice_vals = np.nan_to_num(self.df.loc[idx, self.voice_cols].values.astype(np.float32), nan=0.0)\n",
            "        physio_vals = np.nan_to_num(self.df.loc[idx, self.physio_cols].values.astype(np.float32), nan=0.0)\n",
            "        \n",
            "        face_val = torch.tensor(face_vals, dtype=torch.float32).unsqueeze(0).repeat(self.seq_len, 1)\n",
            "        voice_val = torch.tensor(voice_vals, dtype=torch.float32).unsqueeze(0).repeat(self.seq_len, 1)\n",
            "        physio_val = torch.tensor(physio_vals, dtype=torch.float32).unsqueeze(0).repeat(self.seq_len, 1)\n",
            "        label = torch.tensor(int(self.df.loc[idx, 'label']), dtype=torch.long)\n",
            "        \n",
            "        return {\n",
            "            'face': face_val,\n",
            "            'voice': voice_val,\n",
            "            'physio': physio_val,\n",
            "            'face_mask': face_mask_t,\n",
            "            'voice_mask': voice_mask_t,\n",
            "            'physio_mask': physio_mask_t,\n",
            "            'label': label\n",
            "        }\n",
            "\n",
            "train_ds = SyncedDataset(df_train, is_train=True)\n",
            "val_ds = SyncedDataset(df_val, is_train=False)\n",
            "train_loader = DataLoader(train_ds, batch_size=128, shuffle=True)\n",
            "val_loader = DataLoader(val_ds, batch_size=128, shuffle=False)\n",
            "print(\"[STATUS] Dataloaders constructed successfully.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "print(f\"[INFO] Executing training cycles on target device: {device}\")\n",
            "\n",
            "# Construct a standard train loader (is_train=False) specifically for training baseline models\n",
            "# that do not use training modality dropout.\n",
            "train_ds_standard = SyncedDataset(df_train, is_train=False)\n",
            "train_loader_standard = DataLoader(train_ds_standard, batch_size=128, shuffle=True)\n",
            "\n",
            "print(\"[BACKGROUND] Training 1/5: Early Fusion baseline...\")\n",
            "model_early = EarlyFusionClassifier(face_dim=len(train_ds.face_cols), voice_dim=len(train_ds.voice_cols), physio_dim=len(train_ds.physio_cols))\n",
            "opt_early = torch.optim.Adam(model_early.parameters(), lr=1e-3)\n",
            "trainer_early = MultimodalTrainer(model_early, train_loader_standard, val_loader, opt_early, nn.CrossEntropyLoss(), device, '../outputs/checkpoints/best_early.pt', patience=5)\n",
            "trainer_early.fit(num_epochs=10)\n",
            "\n",
            "print(\"[BACKGROUND] Training 2/5: Gated Fusion baseline...\")\n",
            "model_gated = GatedFusionClassifier(face_dim=len(train_ds.face_cols), voice_dim=len(train_ds.voice_cols), physio_dim=len(train_ds.physio_cols))\n",
            "opt_gated = torch.optim.Adam(model_gated.parameters(), lr=1e-3)\n",
            "trainer_gated = MultimodalTrainer(model_gated, train_loader_standard, val_loader, opt_gated, nn.CrossEntropyLoss(), device, '../outputs/checkpoints/best_gated.pt', patience=5)\n",
            "trainer_gated.fit(num_epochs=10)\n",
            "\n",
            "print(\"[BACKGROUND] Training 3/5: Cross-Attention Fusion baseline...\")\n",
            "model_attn = CrossAttentionFusionClassifier(face_dim=len(train_ds.face_cols), voice_dim=len(train_ds.voice_cols), physio_dim=len(train_ds.physio_cols))\n",
            "opt_attn = torch.optim.Adam(model_attn.parameters(), lr=1e-3)\n",
            "trainer_attn = MultimodalTrainer(model_attn, train_loader_standard, val_loader, opt_attn, nn.CrossEntropyLoss(), device, '../outputs/checkpoints/best_attention.pt', patience=5)\n",
            "trainer_attn.fit(num_epochs=10)\n",
            "\n",
            "print(\"[BACKGROUND] Training 4/5: Standard MoE Fusion (without modality dropout)...\")\n",
            "model_moe_standard = FlexiModalMoE(face_dim=len(train_ds.face_cols), voice_dim=len(train_ds.voice_cols), physio_dim=len(train_ds.physio_cols), num_experts=3)\n",
            "opt_moe_std = torch.optim.Adam(model_moe_standard.parameters(), lr=1e-3)\n",
            "trainer_moe_std = MultimodalTrainer(model_moe_standard, train_loader_standard, val_loader, opt_moe_std, nn.CrossEntropyLoss(), device, '../outputs/checkpoints/best_moe_standard.pt', patience=5)\n",
            "trainer_moe_std.fit(num_epochs=10)\n",
            "\n",
            "print(\"[BACKGROUND] Training 5/5: Robust FlexiModal MoE (with training modality dropout)...\")\n",
            "model_moe_robust = FlexiModalMoE(face_dim=len(train_ds.face_cols), voice_dim=len(train_ds.voice_cols), physio_dim=len(train_ds.physio_cols), num_experts=3)\n",
            "opt_moe_rob = torch.optim.Adam(model_moe_robust.parameters(), lr=1e-3)\n",
            "trainer_moe_rob = MultimodalTrainer(model_moe_robust, train_loader, val_loader, opt_moe_rob, nn.CrossEntropyLoss(), device, '../outputs/checkpoints/best_moe_robust.pt', patience=5)\n",
            "trainer_moe_rob.fit(num_epochs=10)\n",
            "\n",
            "print(\"[STATUS] All 5 models successfully trained and checkpoints saved under early_fusion/outputs/checkpoints/\")"
        ]
    }
]

# ==========================================
# Notebook 4: 04_validate_models.ipynb
# ==========================================
nb4_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 7: Robustness Evaluation (Simulated Missing Modalities)\n",
            "Validates trained checkpoints under partial input dropout scenarios."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Loading test split features...\")\n",
            "import os\n",
            "import sys\n",
            "import torch\n",
            "import pandas as pd\n",
            "from torch.utils.data import DataLoader\n",
            "\n",
            "sys.path.append(os.path.abspath('../'))\n",
            "from src.models.fleximodal_moe import FlexiModalMoE\n",
            "from src.training.trainer import MultimodalTrainer\n",
            "print(\"[STATUS] Validation imports successful.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Reconstructing datasets from test split subjects...\")\n",
            "# Reload data directly from processed test partition\n",
            "df_test = pd.read_csv('../data/processed/test/test_synced.csv')\n",
            "\n",
            "# Redefine TestDataset inline\n",
            "class TestDataset(torch.utils.data.Dataset):\n",
            "    def __init__(self, df, seq_len=5):\n",
            "        self.df = df.reset_index(drop=True)\n",
            "        self.seq_len = seq_len\n",
            "        # Locate feature columns dynamically supporting both real and mock columns\n",
            "        face_cands = ['left_ear', 'right_ear', 'avg_ear', 'blink_velocity', 'brow_descent_left', 'brow_descent_right', 'brow_asymmetry', 'lip_compression', 'jaw_tension', 'mouth_corner_pull', 'forehead_tension', 'face_height_norm', 'head_tilt', 'temporal_x_var', 'temporal_y_var', 'eye_openness_ratio', 'landmark_confidence', 'nose_wrinkle']\n",
            "        self.face_cols = [c for c in face_cands if c in df.columns]\n",
            "        if len(self.face_cols) == 0:\n",
            "            self.face_cols = [c for c in df.columns if c.startswith('face_') and c not in ['face_mask']]\n",
            "            \n",
            "        voice_cands = ['f0_mean', 'f0_std', 'f0_range', 'jitter_percent', 'shimmer_db', 'hnr', 'speaking_rate_proxy', 'voice_intensity', 'high_freq_ratio', 'spectral_flux', 'pause_ratio', 'voiced_fraction']\n",
            "        self.voice_cols = [c for c in voice_cands if c in df.columns]\n",
            "        if len(self.voice_cols) == 0:\n",
            "            self.voice_cols = [c for c in df.columns if c.startswith('voice_') and c not in ['voice_mask']]\n",
            "            \n",
            "        physio_cands = ['ecg_rate_mean', 'ecg_hrv_rmssd', 'ecg_hrv_sdnn', 'eda_scl_mean', 'resp_rate_mean']\n",
            "        self.physio_cols = [c for c in physio_cands if c in df.columns]\n",
            "        if len(self.physio_cols) == 0:\n",
            "            self.physio_cols = [c for c in df.columns if c.startswith('physio_') and c not in ['physio_mask']]\n",
            "        \n",
            "    def __len__(self):\n",
            "        return len(self.df)\n",
            "        \n",
            "    def __getitem__(self, idx):\n",
            "        # Force conversion to float32 and handle NaNs dynamically from left join\n",
            "        face_nans = self.df.loc[idx, self.face_cols].isna().any()\n",
            "        voice_nans = self.df.loc[idx, self.voice_cols].isna().any()\n",
            "        physio_nans = self.df.loc[idx, self.physio_cols].isna().any()\n",
            "        \n",
            "        face_mask = torch.tensor(0.0 if face_nans else 1.0, dtype=torch.float32)\n",
            "        voice_mask = torch.tensor(0.0 if voice_nans else 1.0, dtype=torch.float32)\n",
            "        physio_mask = torch.tensor(0.0 if physio_nans else 1.0, dtype=torch.float32)\n",
            "        \n",
            "        face_vals = np.nan_to_num(self.df.loc[idx, self.face_cols].values.astype(np.float32), nan=0.0)\n",
            "        voice_vals = np.nan_to_num(self.df.loc[idx, self.voice_cols].values.astype(np.float32), nan=0.0)\n",
            "        physio_vals = np.nan_to_num(self.df.loc[idx, self.physio_cols].values.astype(np.float32), nan=0.0)\n",
            "        \n",
            "        face_val = torch.tensor(face_vals, dtype=torch.float32).unsqueeze(0).repeat(self.seq_len, 1)\n",
            "        voice_val = torch.tensor(voice_vals, dtype=torch.float32).unsqueeze(0).repeat(self.seq_len, 1)\n",
            "        physio_val = torch.tensor(physio_vals, dtype=torch.float32).unsqueeze(0).repeat(self.seq_len, 1)\n",
            "        label = torch.tensor(int(self.df.loc[idx, 'label']), dtype=torch.long)\n",
            "        \n",
            "        return {\n",
            "            'face': face_val,\n",
            "            'voice': voice_val,\n",
            "            'physio': physio_val,\n",
            "            'face_mask': face_mask,\n",
            "            'voice_mask': voice_mask,\n",
            "            'physio_mask': physio_mask,\n",
            "            'label': label\n",
            "        }\n",
            "\n",
            "test_ds = TestDataset(df_test)\n",
            "test_loader = DataLoader(test_ds, batch_size=128, shuffle=False)\n",
            "print(f\"[INFO] Test loader configured with {len(test_ds)} sample windows.\")"
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Commencing missing-modality robustness ablation audits for all 5 models...\")\n",
            "import os\n",
            "import time\n",
            "import torch\n",
            "import pandas as pd\n",
            "import numpy as np\n",
            "from sklearn.metrics import accuracy_score, precision_recall_fscore_support, f1_score\n",
            "from src.models.baselines import EarlyFusionClassifier, GatedFusionClassifier, CrossAttentionFusionClassifier\n",
            "from src.models.fleximodal_moe import FlexiModalMoE\n",
            "\n",
            "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"cpu\")\n",
            "face_dim = len(test_ds.face_cols)\n",
            "voice_dim = len(test_ds.voice_cols)\n",
            "physio_dim = len(test_ds.physio_cols)\n",
            "\n",
            "models_info = [\n",
            "    {\"name\": \"Early Fusion Baseline\",        \"class\": \"EarlyFusionClassifier\",        \"ckpt\": \"../outputs/checkpoints/best_early.pt\"},\n",
            "    {\"name\": \"Gated Fusion Baseline\",        \"class\": \"GatedFusionClassifier\",        \"ckpt\": \"../outputs/checkpoints/best_gated.pt\"},\n",
            "    {\"name\": \"Cross-Attention Fusion\",       \"class\": \"CrossAttentionFusionClassifier\", \"ckpt\": \"../outputs/checkpoints/best_attention.pt\"},\n",
            "    {\"name\": \"Standard MoE Fusion\",          \"class\": \"FlexiModalMoE\",                \"ckpt\": \"../outputs/checkpoints/best_moe_standard.pt\"},\n",
            "    {\"name\": \"Robust FlexiModal MoE\",        \"class\": \"FlexiModalMoE\",                \"ckpt\": \"../outputs/checkpoints/best_moe_robust.pt\"}\n",
            "]\n",
            "\n",
            "scenarios = [\n",
            "    {\"name\": \"All Modalities Present\", \"face\": 1.0, \"voice\": 1.0, \"physio\": 1.0},\n",
            "    {\"name\": \"Missing Face/Video\",     \"face\": 0.0, \"voice\": 1.0, \"physio\": 1.0},\n",
            "    {\"name\": \"Missing Voice/Audio\",    \"face\": 1.0, \"voice\": 0.0, \"physio\": 1.0},\n",
            "    {\"name\": \"Missing Physio Logs\",    \"face\": 1.0, \"voice\": 1.0, \"physio\": 0.0},\n",
            "]\n",
            "\n",
            "results = []\n",
            "for m_info in models_info:\n",
            "    print(f\"\\n[AUDIT] Evaluating: {m_info['name']}...\")\n",
            "    if not os.path.exists(m_info[\"ckpt\"]):\n",
            "        print(f\"  [WARNING] Checkpoint {m_info['ckpt']} not found. Skipping.\")\n",
            "        continue\n",
            "        \n",
            "    # Instantiate model\n",
            "    if m_info[\"class\"] == \"EarlyFusionClassifier\":\n",
            "        model = EarlyFusionClassifier(face_dim, voice_dim, physio_dim)\n",
            "    elif m_info[\"class\"] == \"GatedFusionClassifier\":\n",
            "        model = GatedFusionClassifier(face_dim, voice_dim, physio_dim)\n",
            "    elif m_info[\"class\"] == \"CrossAttentionFusionClassifier\":\n",
            "        model = CrossAttentionFusionClassifier(face_dim, voice_dim, physio_dim)\n",
            "    elif m_info[\"class\"] == \"FlexiModalMoE\":\n",
            "        model = FlexiModalMoE(face_dim, voice_dim, physio_dim, num_experts=3)\n",
            "        \n",
            "    # Load weights\n",
            "    ckpt = torch.load(m_info[\"ckpt\"], map_location=device, weights_only=False)\n",
            "    model.load_state_dict(ckpt[\"model_state_dict\"])\n",
            "    model.to(device)\n",
            "    model.eval()\n",
            "    \n",
            "    # Trainable parameters count\n",
            "    num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n",
            "    \n",
            "    # Measure latency\n",
            "    latencies = []\n",
            "    dummy_face = torch.randn(1, 5, face_dim).to(device)\n",
            "    dummy_voice = torch.randn(1, 5, voice_dim).to(device)\n",
            "    dummy_physio = torch.randn(1, 5, physio_dim).to(device)\n",
            "    dummy_mask = torch.tensor([1.0]).to(device)\n",
            "    \n",
            "    # Warm-up\n",
            "    for _ in range(5):\n",
            "        with torch.no_grad():\n",
            "            if m_info[\"class\"] == \"FlexiModalMoE\":\n",
            "                _ = model(dummy_face, dummy_voice, dummy_physio, dummy_mask, dummy_mask, dummy_mask)\n",
            "            else:\n",
            "                _ = model(dummy_face, dummy_voice, dummy_physio)\n",
            "                \n",
            "    # Measure forward pass time\n",
            "    for _ in range(50):\n",
            "        start_time = time.time()\n",
            "        with torch.no_grad():\n",
            "            if m_info[\"class\"] == \"FlexiModalMoE\":\n",
            "                _ = model(dummy_face, dummy_voice, dummy_physio, dummy_mask, dummy_mask, dummy_mask)\n",
            "            else:\n",
            "                _ = model(dummy_face, dummy_voice, dummy_physio)\n",
            "        latencies.append((time.time() - start_time) * 1000.0)\n",
            "    avg_latency = np.mean(latencies)\n",
            "    \n",
            "    # Evaluate on test dataset splits per missing modality scenario\n",
            "    for scen in scenarios:\n",
            "        correct = 0\n",
            "        total = 0\n",
            "        for batch in test_loader:\n",
            "            face_x = batch['face'].to(device)\n",
            "            voice_x = batch['voice'].to(device)\n",
            "            physio_x = batch['physio'].to(device)\n",
            "            labels = batch['label'].to(device)\n",
            "            \n",
            "            f_mask = torch.tensor([scen['face']]*face_x.size(0), device=device)\n",
            "            v_mask = torch.tensor([scen['voice']]*voice_x.size(0), device=device)\n",
            "            p_mask = torch.tensor([scen['physio']]*physio_x.size(0), device=device)\n",
            "            \n",
            "            with torch.no_grad():\n",
            "                if m_info[\"class\"] == \"FlexiModalMoE\":\n",
            "                    logits, _ = model(face_x, voice_x, physio_x, f_mask, v_mask, p_mask)\n",
            "                else:\n",
            "                    # Manual masking for baselines\n",
            "                    face_in = face_x * f_mask.view(-1, 1, 1)\n",
            "                    voice_in = voice_x * v_mask.view(-1, 1, 1)\n",
            "                    physio_in = physio_x * p_mask.view(-1, 1, 1)\n",
            "                    logits = model(face_in, voice_in, physio_in)\n",
            "                preds = torch.argmax(logits, dim=-1)\n",
            "                all_preds.extend(preds.cpu().numpy())\n",
            "                all_labels.extend(labels.cpu().numpy())\n",
            "                \n",
            "        all_labels = np.array(all_labels)\n",
            "        all_preds = np.array(all_preds)\n",
            "        \n",
            "        acc = accuracy_score(all_labels, all_preds)\n",
            "        macro_f1 = f1_score(all_labels, all_preds, average='macro')\n",
            "        \n",
            "        # Per-class precision, recall, f1-score\n",
            "        prec, rec, f1, _ = precision_recall_fscore_support(all_labels, all_preds, labels=[0, 1], zero_division=0)\n",
            "        \n",
            "        results.append({\n",
            "            \"Model\": m_info[\"name\"],\n",
            "            \"Parameters\": num_params,\n",
            "            \"Latency (ms)\": f\"{avg_latency:.3f}ms\",\n",
            "            \"Scenario\": scen[\"name\"],\n",
            "            \"Accuracy\": f\"{acc*100:.2f}%\",\n",
            "            \"Macro F1\": f\"{macro_f1*100:.2f}%\",\n",
            "            \"Relaxed Prec (C0)\": f\"{prec[0]*100:.2f}%\",\n",
            "            \"Relaxed Rec (C0)\": f\"{rec[0]*100:.2f}%\",\n",
            "            \"Relaxed F1 (C0)\": f\"{f1[0]*100:.2f}%\",\n",
            "            \"Stressed Prec (C1)\": f\"{prec[1]*100:.2f}%\",\n",
            "            \"Stressed Rec (C1)\": f\"{rec[1]*100:.2f}%\",\n",
            "            \"Stressed F1 (C1)\": f\"{f1[1]*100:.2f}%\"\n",
            "        })\n",
            "        \n",
            "results_df = pd.DataFrame(results)\n",
            "os.makedirs('../reports/evaluation/', exist_ok=True)\n",
            "results_df.to_csv('../reports/evaluation/robustness_metrics.csv', index=False)\n",
            "print(\"[STATUS] All 5 models evaluated and ablation study metrics saved to robustness_metrics.csv.\")"
        ]
    }
]

# ==========================================
# Notebook 5: 05_final_report.ipynb
# ==========================================
nb5_cells = [
    {
        "cell_type": "markdown",
        "metadata": {},
        "source": [
            "# Phase 8: Final Model Selection & Comparison\n",
            "Summarizes parameter sizes, model inference results, and final synchronization metrics."
        ]
    },
    {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": [
            "print(\"[BACKGROUND] Collecting final comparison data...\")\n",
            "import os\n",
            "import pandas as pd\n",
            "\n",
            "eval_csv = '../reports/evaluation/robustness_metrics.csv'\n",
            "if os.path.exists(eval_csv):\n",
            "    df = pd.read_csv(eval_csv)\n",
            "    # Sort for cleaner, structured presentation by model and scenario\n",
            "    df_sorted = df.sort_values(by=['Model', 'Scenario'])\n",
            "    \n",
            "    # Print to console\n",
            "    print(\"\\n=============================================================================================================================\")\n",
            "    print(\"STAGE 8: MULTIMODAL ROBUSTNESS & ABLATION COMPARISON STUDY (ALL CLASSES & MODALITIES)\")\n",
            "    print(\"=============================================================================================================================\")\n",
            "    print(df_sorted.to_string(index=False))\n",
            "    print(\"=============================================================================================================================\")\n",
            "    \n",
            "    # Export beautiful markdown report\n",
            "    md_table = df_sorted.to_markdown(index=False)\n",
            "    report_md = f\"\"\"# Stage 8: Multimodal Ablation Study & Robustness Comparison\\n\\n\"\n",
            "    report_md += \"This report summarizes the comparative performance, class-specific metrics, architectural sizes, and inference latency costs of the five trained architectures under various sensor dropout (missing modality) scenarios.\\n\\n\"\n",
            "    report_md += f\"\\n{md_table}\\n\"\n",
            "    os.makedirs('../reports/evaluation/', exist_ok=True)\n",
            "    with open('../reports/evaluation/ablation_study_report.md', 'w') as f:\n",
            "        f.write(report_md)\n",
            "    print(\"[STATUS] Formatted ablation report successfully saved to reports/evaluation/ablation_study_report.md\")\n",
            "else:\n",
            "    print(\"[WARNING] Robustness CSV report not found. Execute Notebook 04 first.\")\n",
            "\n",
            "print(\"[STATUS] Project final select reporting finished successfully.\")"
        ]
    }
]

if __name__ == '__main__':
    script_dir = os.path.dirname(os.path.abspath(__file__))
    early_fusion_dir = os.path.dirname(script_dir)
    
    write_notebook(os.path.join(early_fusion_dir, 'notebooks', '01_raw_sync_audit.ipynb'), nb1_cells)
    write_notebook(os.path.join(early_fusion_dir, 'notebooks', '02_extract_and_align.ipynb'), nb2_cells)
    write_notebook(os.path.join(early_fusion_dir, 'notebooks', '03_train_models.ipynb'), nb3_cells)
    write_notebook(os.path.join(early_fusion_dir, 'notebooks', '04_validate_models.ipynb'), nb4_cells)
    write_notebook(os.path.join(early_fusion_dir, 'notebooks', '05_final_report.ipynb'), nb5_cells)
